# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer1.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    extra_hosts:
      - "peer0.org1.example.com:192.168.56.2"
      - "peer1.org1.example.com:192.168.56.2"
      - "peer0.org2.example.com:192.168.56.3"
      - "peer1.org2.example.com:192.168.56.3"
      - "orderer0.example.com:192.168.56.4"
      - "orderer1.example.com:0.0.0.0"
      - "orderer2.example.com:192.168.56.6"
      - "kafka0.example.com:192.168.56.4"
      - "kafka1.example.com:0.0.0.0"
      - "kafka2.example.com:192.168.56.6"
      - "kafka3.example.com:192.168.56.6"
      - "zookeeper0.example.com:192.168.56.4"
      - "zookeeper1.example.com:0.0.0.0"
      - "zookeeper2.example.com:192.168.56.6"