version: '2'

volumes:
    orderer.example.com:

networks:
    byfn:

services:
    orderer.example.com:
        extends:
            file:   base/docker-compose-base.yaml
            service: orderer.example.com
        container_name: orderer0.example.com
        networks:
            - byfn

    zookeeper0:
        container_name: zookeeper0
        image: hyperledger/fabric-zookeeper
        environment:
            - ZOO_MY_ID = 1
            - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=192.168.56.105:2888:3888 server.3=192.168.56.106:2888:3888
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        networks:
            - byfn
        extra_hosts:
            - zookeeper1:192.168.56.105
            - zookeeper2:192.168.56.106

    kafka0:
        container_name: kafka0
        image: hyperledger/fabric-kafka
        environment:
            - KAFKA_BROKER_ID=0
            - KAFKA_ADVERTISED_HOST_NAME=192.168.56.104
            - KAFKA_ADVERTISED_PORT=9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_MESSAGE_MAX_BYTES=1048576
            - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_DEFAULT_REPLICATION_FACTOR=4
            - KAFKA_MIN_INSYNC_REPLICAS=1
        ports:
            - 9092:9092
        networks:
            - byfn
        extra_hosts:
            - zookeeper1:192.168.56.105
            - zookeeper2:192.168.56.106
        depends_on:
            - zookeeper0